<%@ Page Language="VB" AutoEventWireup="false" CodeFile="menu_login.aspx.vb" Inherits="menu_login" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <title>Untitled Page</title>
    <link href="css/estilo.css" type="text/css" rel="stylesheet"/>
</head>
<body>
    <form id="form1" runat="server">
        <asp:TreeView ID="treeMenu" runat="server" ImageSet="Simple" ExpandDepth="0" Font-Names="Verdana" Font-Size="X-Small" AutoGenerateDataBindings="False" CssClass="texto" Width="180px">
            <ParentNodeStyle Font-Bold="False" Font-Names="verdana,arial,helvetica,sans-serif" Font-Size="X-Small" />
            <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" Font-Bold="False" Font-Size="X-Small" />
            <SelectedNodeStyle Font-Underline="True" ForeColor="#8080FF" HorizontalPadding="0px"
                VerticalPadding="0px" Font-Bold="False" />
            <NodeStyle Font-Names="Verdana,Arial,Helvetica,sans-serif" Font-Size="X-Small" ForeColor="Black" HorizontalPadding="0px"
                NodeSpacing="0px" VerticalPadding="0px" Font-Bold="False" />
            <LeafNodeStyle Font-Size="X-Small" />
            <RootNodeStyle Font-Size="X-Small" />
        </asp:TreeView>
    </form>
</body>
</html>

